all:	lanczos_tempos.png\
		lanczos_speedup.png

lanczos_tempos.png: plota_grafico_tempos.gp
	gnuplot plota_grafico_tempos.gp
	eog lanczos_tempos.png

lanczos_speedup.png: plota_grafico_speedup.gp
	gnuplot plota_grafico_speedup.gp
	eog lanczos_speedup.png
